const links = { 
    'index': 'installation/index.html', 
    'quickstart': 'quickstart.html', 
    'about': 'about.html', 'whats new': 
    'whats-new.html', 'environment': 
    'mastrogpt/environment.html', 
    'devel': 'mastrogpt/devel.html', 
    'deploy': 'mastrogpt/deploy.html', 
    'getting started': 
    'tutorial/getting-started.html', 
    'first steps': 'tutorial/first-steps.html', 
    'form validation': 'tutorial/form-validation.html', 
    'use database': 'tutorial/use-database.html', 
    'notify message': 'tutorial/notify-message.html', 
    'packaging': 'tutorial/packaging.html', 
    'index entities': 'development/index-entities.html', 
    'actions': 'cli/actions.html', 
    'webactions': 'development/webactions.html', 
    'parameters': 'development/parameters.html', 
    'annotations': 'development/annotations.html', 
    'scheduler': 'development/scheduler.html', 
    'packages': 'cli/packages.html', 
    'feeds': 'development/feeds.html', 
    'index runtimes': 'development/index-runtimes.html', 
    'actions nodejs': 'development/actions-nodejs.html', 
    'actions python': 'development/actions-python.html', 
    'actions go': 'development/actions-go.html', 
    'actions java': 'development/actions-java.html', 
    'actions php': 'development/actions-php.html', 
    'index references': 'development/index-references.html', 
    'rest_api': 'development/rest_api.html', 
    'cli': 'development/cli.html', 'reference': 
    'development/reference.html', 'actions new': 
    'development/actions-new.html', 
    'actions actionloop': 
    'development/actions-actionloop.html', 
    'entities': 'cli/entities.html', 
    'activations': 'cli/activations.html', 
    'sequences': 'cli/sequences.html', 
    'triggers': 'cli/triggers.html', 
    'rules': 'cli/rules.html', 'project': 
    'cli/project.html', 
    'admin': 'cli/admin.html', 
    'debug': 'installation/debug.html', 
    'download': 'installation/download.html', 
    'prereq': 'installation/prereq.html', 
    'prereq docker': 'installation/prereq-docker.html', 
    'prereq server generic': 'installation/prereq-server-generic.html', 
    'prereq server aws': 'installation/prereq-server-aws.html', 
    'prereq server gcp': 'installation/prereq-server-gcp.html', 
    'prereq k3s': 'installation/prereq-k3s.html', 
    'prereq mk8s': 'installation/prereq-mk8s.html', 
    'prereq kubernetes': 'installation/prereq-kubernetes.html', 
    'prereq eks': 'installation/prereq-eks.html',
    'prereq aks': 'installation/prereq-aks.html', 
    'prereq gke': 'installation/prereq-gke.html', 
    'prereq osh': 'installation/prereq-osh.html', 
    'prereq cluster': 'installation/prereq-cluster.html', 
    'configure': 'installation/configure.html', 
    'configure dns': 'installation/configure-dns.html', 
    'configure services': 'installation/configure-services.html', 
    'install': 'installation/install.html', 
    'install local': 'installation/install-local.html', 
    'install server': 'installation/install-server.html', 
    'install cluster': 'installation/install-cluster.html' 
}